/* Generated By:JavaCC: Do not edit this line. JavaCCTableParserConstants.java */
package be.devijver.wikipedia.parser.javacc.table;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCTableParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TABLE_START = 39;
  /** RegularExpression Id. */
  int TABLE_END = 40;
  /** RegularExpression Id. */
  int START_PRE_NOWIKI = 41;
  /** RegularExpression Id. */
  int START_COMMENT = 42;
  /** RegularExpression Id. */
  int MULTI = 43;
  /** RegularExpression Id. */
  int NOWIKI_CHARACTER = 48;
  /** RegularExpression Id. */
  int END_PRE_NOWIKI = 49;
  /** RegularExpression Id. */
  int MULTI_CHARACTER = 50;
  /** RegularExpression Id. */
  int END_MULTI = 51;
  /** RegularExpression Id. */
  int CHARACTER = 52;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT = 1;
  /** Lexical state. */
  int NOWIKI = 2;
  /** Lexical state. */
  int MULTI_LINE = 3;

  /** Literal token values. */
  String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n|+\"", "\"|\"", "\"\\n\"", "\"\\n|-\"", "\"-\"", "\"!\"",
      "\"!!\"", "\"||\"", "\"{\"", "\"}\"", "\"=\"", "\"\\\'\"", "\":\"", "\"%\"", "\"#\"", "\";\"", "\"\\\"\"",
      "\"<br>\\n\"", "\",\"", "\"[\"", "\"]\"", "\"(\"", "\")\"", "\".\"", "\"?\"", "\"/\"", "\"\\\\\"", "\"+\"",
      "\"<\"", "\">\"", "\"*\"", "\"$\"", "\"_\"", "\"&\"", "\"`\"", "\"~\"", "\"{|\"", "\"|}\"", "\"<pre><nowiki>\"",
      "\"<!--\"", "\"<multi>\"", "<token of kind 44>", "<token of kind 45>", "\"-->\"", "\"-\"", "<NOWIKI_CHARACTER>",
      "\"</nowiki></pre>\"", "<MULTI_CHARACTER>", "\"</multi>\"", "<CHARACTER>", };

}
