/* Generated By:JavaCC: Do not edit this line. JavaCCTableParserTokenManager.java */
package be.devijver.wikipedia.parser.javacc.table;

import java.util.*;
import be.devijver.wikipedia.parser.ast.*;

/** Token Manager. */
public class JavaCCTableParserTokenManager implements JavaCCTableParserConstants {

  /** Debug output. */
  public java.io.PrintStream debugStream = System.out;

  /** Set debug output. */
  public void setDebugStream(java.io.PrintStream ds) {
    debugStream = ds;
  }

  private final int jjStopStringLiteralDfa_0(int pos, long active0) {
    switch (pos) {
    default:
      return -1;
    }
  }

  private final int jjStartNfa_0(int pos, long active0) {
    return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
  }

  private int jjStopAtPos(int pos, int kind) {
    jjmatchedKind = kind;
    jjmatchedPos = pos;
    return pos + 1;
  }

  private int jjMoveStringLiteralDfa0_0() {
    switch (curChar) {
    case 9:
      return jjStopAtPos(0, 2);
    case 10:
      jjmatchedKind = 5;
      return jjMoveStringLiteralDfa1_0(0x48L);
    case 32:
      return jjStopAtPos(0, 1);
    case 33:
      jjmatchedKind = 8;
      return jjMoveStringLiteralDfa1_0(0x200L);
    case 34:
      return jjStopAtPos(0, 19);
    case 35:
      return jjStopAtPos(0, 17);
    case 36:
      return jjStopAtPos(0, 34);
    case 37:
      return jjStopAtPos(0, 16);
    case 38:
      return jjStopAtPos(0, 36);
    case 39:
      return jjStopAtPos(0, 14);
    case 40:
      return jjStopAtPos(0, 24);
    case 41:
      return jjStopAtPos(0, 25);
    case 42:
      return jjStopAtPos(0, 33);
    case 43:
      return jjStopAtPos(0, 30);
    case 44:
      return jjStopAtPos(0, 21);
    case 45:
      return jjStopAtPos(0, 7);
    case 46:
      return jjStopAtPos(0, 26);
    case 47:
      return jjStopAtPos(0, 28);
    case 58:
      return jjStopAtPos(0, 15);
    case 59:
      return jjStopAtPos(0, 18);
    case 60:
      jjmatchedKind = 31;
      return jjMoveStringLiteralDfa1_0(0xe0000100000L);
    case 61:
      return jjStopAtPos(0, 13);
    case 62:
      return jjStopAtPos(0, 32);
    case 63:
      return jjStopAtPos(0, 27);
    case 91:
      return jjStopAtPos(0, 22);
    case 92:
      return jjStopAtPos(0, 29);
    case 93:
      return jjStopAtPos(0, 23);
    case 95:
      return jjStopAtPos(0, 35);
    case 96:
      return jjStopAtPos(0, 37);
    case 123:
      jjmatchedKind = 11;
      return jjMoveStringLiteralDfa1_0(0x8000000000L);
    case 124:
      jjmatchedKind = 4;
      return jjMoveStringLiteralDfa1_0(0x10000000400L);
    case 125:
      return jjStopAtPos(0, 12);
    case 126:
      return jjStopAtPos(0, 38);
    default:
      return jjMoveNfa_0(0, 0);
    }
  }

  private int jjMoveStringLiteralDfa1_0(long active0) {
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
    }
    switch (curChar) {
    case 33:
      if ((active0 & 0x200L) != 0L)
        return jjStopAtPos(1, 9);
      return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
    case 98:
      return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
    case 109:
      return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L);
    case 112:
      return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
    case 124:
      if ((active0 & 0x400L) != 0L)
        return jjStopAtPos(1, 10);
      else if ((active0 & 0x8000000000L) != 0L)
        return jjStopAtPos(1, 39);
      return jjMoveStringLiteralDfa2_0(active0, 0x48L);
    case 125:
      if ((active0 & 0x10000000000L) != 0L)
        return jjStopAtPos(1, 40);
      break;
    default:
      break;
    }
    return jjStartNfa_0(0, active0);
  }

  private int jjMoveStringLiteralDfa2_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
    }
    switch (curChar) {
    case 43:
      if ((active0 & 0x8L) != 0L)
        return jjStopAtPos(2, 3);
      break;
    case 45:
      if ((active0 & 0x40L) != 0L)
        return jjStopAtPos(2, 6);
      return jjMoveStringLiteralDfa3_0(active0, 0x40000000000L);
    case 114:
      return jjMoveStringLiteralDfa3_0(active0, 0x20000100000L);
    case 117:
      return jjMoveStringLiteralDfa3_0(active0, 0x80000000000L);
    default:
      break;
    }
    return jjStartNfa_0(1, active0);
  }

  private int jjMoveStringLiteralDfa3_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
    }
    switch (curChar) {
    case 45:
      if ((active0 & 0x40000000000L) != 0L)
        return jjStopAtPos(3, 42);
      break;
    case 62:
      return jjMoveStringLiteralDfa4_0(active0, 0x100000L);
    case 101:
      return jjMoveStringLiteralDfa4_0(active0, 0x20000000000L);
    case 108:
      return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L);
    default:
      break;
    }
    return jjStartNfa_0(2, active0);
  }

  private int jjMoveStringLiteralDfa4_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
    }
    switch (curChar) {
    case 10:
      if ((active0 & 0x100000L) != 0L)
        return jjStopAtPos(4, 20);
      break;
    case 62:
      return jjMoveStringLiteralDfa5_0(active0, 0x20000000000L);
    case 116:
      return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L);
    default:
      break;
    }
    return jjStartNfa_0(3, active0);
  }

  private int jjMoveStringLiteralDfa5_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
    }
    switch (curChar) {
    case 60:
      return jjMoveStringLiteralDfa6_0(active0, 0x20000000000L);
    case 105:
      return jjMoveStringLiteralDfa6_0(active0, 0x80000000000L);
    default:
      break;
    }
    return jjStartNfa_0(4, active0);
  }

  private int jjMoveStringLiteralDfa6_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
    }
    switch (curChar) {
    case 62:
      if ((active0 & 0x80000000000L) != 0L)
        return jjStopAtPos(6, 43);
      break;
    case 110:
      return jjMoveStringLiteralDfa7_0(active0, 0x20000000000L);
    default:
      break;
    }
    return jjStartNfa_0(5, active0);
  }

  private int jjMoveStringLiteralDfa7_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
    }
    switch (curChar) {
    case 111:
      return jjMoveStringLiteralDfa8_0(active0, 0x20000000000L);
    default:
      break;
    }
    return jjStartNfa_0(6, active0);
  }

  private int jjMoveStringLiteralDfa8_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
    }
    switch (curChar) {
    case 119:
      return jjMoveStringLiteralDfa9_0(active0, 0x20000000000L);
    default:
      break;
    }
    return jjStartNfa_0(7, active0);
  }

  private int jjMoveStringLiteralDfa9_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
    }
    switch (curChar) {
    case 105:
      return jjMoveStringLiteralDfa10_0(active0, 0x20000000000L);
    default:
      break;
    }
    return jjStartNfa_0(8, active0);
  }

  private int jjMoveStringLiteralDfa10_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
    }
    switch (curChar) {
    case 107:
      return jjMoveStringLiteralDfa11_0(active0, 0x20000000000L);
    default:
      break;
    }
    return jjStartNfa_0(9, active0);
  }

  private int jjMoveStringLiteralDfa11_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(9, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0);
      return 11;
    }
    switch (curChar) {
    case 105:
      return jjMoveStringLiteralDfa12_0(active0, 0x20000000000L);
    default:
      break;
    }
    return jjStartNfa_0(10, active0);
  }

  private int jjMoveStringLiteralDfa12_0(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(10, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0);
      return 12;
    }
    switch (curChar) {
    case 62:
      if ((active0 & 0x20000000000L) != 0L)
        return jjStopAtPos(12, 41);
      break;
    default:
      break;
    }
    return jjStartNfa_0(11, active0);
  }

  static final long[] jjbitVec0 = { 0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL };
  static final long[] jjbitVec2 = { 0x0L, 0x0L, 0xffff000000000000L, 0xff7fffffffffffffL };

  private int jjMoveNfa_0(int startState, int curPos) {
    int startsAt = 0;
    jjnewStateCnt = 1;
    int i = 1;
    jjstateSet[0] = startState;
    int kind = 0x7fffffff;
    for (;;) {
      if (++jjround == 0x7fffffff)
        ReInitRounds();
      if (curChar < 64) {
        long l = 1L << curChar;
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if ((0x3ff001000000000L & l) != 0L)
              kind = 52;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else if (curChar < 128) {
        long l = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if ((0x7fffffe87fffffeL & l) != 0L)
              kind = 52;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else {
        int hiByte = (int) (curChar >> 8);
        int i1 = hiByte >> 6;
        long l1 = 1L << (hiByte & 077);
        int i2 = (curChar & 0xff) >> 6;
        long l2 = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 52)
              kind = 52;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      }
      if (kind != 0x7fffffff) {
        jjmatchedKind = kind;
        jjmatchedPos = curPos;
        kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
        return curPos;
      try {
        curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
        return curPos;
      }
    }
  }

  private final int jjStopStringLiteralDfa_3(int pos, long active0) {
    switch (pos) {
    case 0:
      if ((active0 & 0x8000000000000L) != 0L) {
        jjmatchedKind = 50;
        return -1;
      }
      return -1;
    case 1:
      if ((active0 & 0x8000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 50;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 2:
      if ((active0 & 0x8000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 50;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 3:
      if ((active0 & 0x8000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 50;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 4:
      if ((active0 & 0x8000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 50;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 5:
      if ((active0 & 0x8000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 50;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 6:
      if ((active0 & 0x8000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 50;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    default:
      return -1;
    }
  }

  private final int jjStartNfa_3(int pos, long active0) {
    return jjMoveNfa_3(jjStopStringLiteralDfa_3(pos, active0), pos + 1);
  }

  private int jjMoveStringLiteralDfa0_3() {
    switch (curChar) {
    case 60:
      return jjMoveStringLiteralDfa1_3(0x8000000000000L);
    default:
      return jjMoveNfa_3(0, 0);
    }
  }

  private int jjMoveStringLiteralDfa1_3(long active0) {
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_3(0, active0);
      return 1;
    }
    switch (curChar) {
    case 47:
      return jjMoveStringLiteralDfa2_3(active0, 0x8000000000000L);
    default:
      break;
    }
    return jjStartNfa_3(0, active0);
  }

  private int jjMoveStringLiteralDfa2_3(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_3(0, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_3(1, active0);
      return 2;
    }
    switch (curChar) {
    case 109:
      return jjMoveStringLiteralDfa3_3(active0, 0x8000000000000L);
    default:
      break;
    }
    return jjStartNfa_3(1, active0);
  }

  private int jjMoveStringLiteralDfa3_3(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_3(1, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_3(2, active0);
      return 3;
    }
    switch (curChar) {
    case 117:
      return jjMoveStringLiteralDfa4_3(active0, 0x8000000000000L);
    default:
      break;
    }
    return jjStartNfa_3(2, active0);
  }

  private int jjMoveStringLiteralDfa4_3(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_3(2, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_3(3, active0);
      return 4;
    }
    switch (curChar) {
    case 108:
      return jjMoveStringLiteralDfa5_3(active0, 0x8000000000000L);
    default:
      break;
    }
    return jjStartNfa_3(3, active0);
  }

  private int jjMoveStringLiteralDfa5_3(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_3(3, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_3(4, active0);
      return 5;
    }
    switch (curChar) {
    case 116:
      return jjMoveStringLiteralDfa6_3(active0, 0x8000000000000L);
    default:
      break;
    }
    return jjStartNfa_3(4, active0);
  }

  private int jjMoveStringLiteralDfa6_3(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_3(4, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_3(5, active0);
      return 6;
    }
    switch (curChar) {
    case 105:
      return jjMoveStringLiteralDfa7_3(active0, 0x8000000000000L);
    default:
      break;
    }
    return jjStartNfa_3(5, active0);
  }

  private int jjMoveStringLiteralDfa7_3(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_3(5, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_3(6, active0);
      return 7;
    }
    switch (curChar) {
    case 62:
      if ((active0 & 0x8000000000000L) != 0L)
        return jjStopAtPos(7, 51);
      break;
    default:
      break;
    }
    return jjStartNfa_3(6, active0);
  }

  private int jjMoveNfa_3(int startState, int curPos) {
    int startsAt = 0;
    jjnewStateCnt = 1;
    int i = 1;
    jjstateSet[0] = startState;
    int kind = 0x7fffffff;
    for (;;) {
      if (++jjround == 0x7fffffff)
        ReInitRounds();
      if (curChar < 64) {
        long l = 1L << curChar;
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if ((0xffffffff00000600L & l) != 0L)
              kind = 50;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else if (curChar < 128) {
        long l = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if ((0x7fffffffbffffffeL & l) != 0L)
              kind = 50;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else {
        int hiByte = (int) (curChar >> 8);
        int i1 = hiByte >> 6;
        long l1 = 1L << (hiByte & 077);
        int i2 = (curChar & 0xff) >> 6;
        long l2 = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 50)
              kind = 50;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      }
      if (kind != 0x7fffffff) {
        jjmatchedKind = kind;
        jjmatchedPos = curPos;
        kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
        return curPos;
      try {
        curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
        return curPos;
      }
    }
  }

  private final int jjStopStringLiteralDfa_1(int pos, long active0) {
    switch (pos) {
    case 0:
      if ((active0 & 0xc00000000000L) != 0L)
        return 2;
      return -1;
    default:
      return -1;
    }
  }

  private final int jjStartNfa_1(int pos, long active0) {
    return jjMoveNfa_1(jjStopStringLiteralDfa_1(pos, active0), pos + 1);
  }

  private int jjMoveStringLiteralDfa0_1() {
    switch (curChar) {
    case 45:
      jjmatchedKind = 47;
      return jjMoveStringLiteralDfa1_1(0x400000000000L);
    default:
      return jjMoveNfa_1(1, 0);
    }
  }

  private int jjMoveStringLiteralDfa1_1(long active0) {
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_1(0, active0);
      return 1;
    }
    switch (curChar) {
    case 45:
      return jjMoveStringLiteralDfa2_1(active0, 0x400000000000L);
    default:
      break;
    }
    return jjStartNfa_1(0, active0);
  }

  private int jjMoveStringLiteralDfa2_1(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_1(0, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_1(1, active0);
      return 2;
    }
    switch (curChar) {
    case 62:
      if ((active0 & 0x400000000000L) != 0L)
        return jjStopAtPos(2, 46);
      break;
    default:
      break;
    }
    return jjStartNfa_1(1, active0);
  }

  static final long[] jjbitVec3 = { 0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL };

  private int jjMoveNfa_1(int startState, int curPos) {
    int startsAt = 0;
    jjnewStateCnt = 3;
    int i = 1;
    jjstateSet[0] = startState;
    int kind = 0x7fffffff;
    for (;;) {
      if (++jjround == 0x7fffffff)
        ReInitRounds();
      if (curChar < 64) {
        long l = 1L << curChar;
        do {
          switch (jjstateSet[--i]) {
          case 1:
            if ((0xffffdfffffffffffL & l) != 0L) {
              if (kind > 44)
                kind = 44;
              jjCheckNAdd(0);
            } else if (curChar == 45)
              jjCheckNAdd(2);
            break;
          case 0:
            if ((0xffffdfffffffffffL & l) == 0L)
              break;
            if (kind > 44)
              kind = 44;
            jjCheckNAdd(0);
            break;
          case 2:
            if ((0xffffdfffffffffffL & l) == 0L)
              break;
            if (kind > 45)
              kind = 45;
            jjCheckNAdd(2);
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else if (curChar < 128) {
        long l = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 1:
          case 0:
            if (kind > 44)
              kind = 44;
            jjCheckNAdd(0);
            break;
          case 2:
            if (kind > 45)
              kind = 45;
            jjstateSet[jjnewStateCnt++] = 2;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else {
        int hiByte = (int) (curChar >> 8);
        int i1 = hiByte >> 6;
        long l1 = 1L << (hiByte & 077);
        int i2 = (curChar & 0xff) >> 6;
        long l2 = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 1:
          case 0:
            if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
              break;
            if (kind > 44)
              kind = 44;
            jjCheckNAdd(0);
            break;
          case 2:
            if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
              break;
            if (kind > 45)
              kind = 45;
            jjstateSet[jjnewStateCnt++] = 2;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      }
      if (kind != 0x7fffffff) {
        jjmatchedKind = kind;
        jjmatchedPos = curPos;
        kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
        return curPos;
      try {
        curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
        return curPos;
      }
    }
  }

  private final int jjStopStringLiteralDfa_2(int pos, long active0) {
    switch (pos) {
    case 0:
      if ((active0 & 0x2000000000000L) != 0L) {
        jjmatchedKind = 48;
        return -1;
      }
      return -1;
    case 1:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 2:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 3:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 4:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 5:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 6:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 7:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 8:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 9:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 10:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 11:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 12:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    case 13:
      if ((active0 & 0x2000000000000L) != 0L) {
        if (jjmatchedPos == 0) {
          jjmatchedKind = 48;
          jjmatchedPos = 0;
        }
        return -1;
      }
      return -1;
    default:
      return -1;
    }
  }

  private final int jjStartNfa_2(int pos, long active0) {
    return jjMoveNfa_2(jjStopStringLiteralDfa_2(pos, active0), pos + 1);
  }

  private int jjMoveStringLiteralDfa0_2() {
    switch (curChar) {
    case 60:
      return jjMoveStringLiteralDfa1_2(0x2000000000000L);
    default:
      return jjMoveNfa_2(0, 0);
    }
  }

  private int jjMoveStringLiteralDfa1_2(long active0) {
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(0, active0);
      return 1;
    }
    switch (curChar) {
    case 47:
      return jjMoveStringLiteralDfa2_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(0, active0);
  }

  private int jjMoveStringLiteralDfa2_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(0, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(1, active0);
      return 2;
    }
    switch (curChar) {
    case 110:
      return jjMoveStringLiteralDfa3_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(1, active0);
  }

  private int jjMoveStringLiteralDfa3_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(1, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(2, active0);
      return 3;
    }
    switch (curChar) {
    case 111:
      return jjMoveStringLiteralDfa4_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(2, active0);
  }

  private int jjMoveStringLiteralDfa4_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(2, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(3, active0);
      return 4;
    }
    switch (curChar) {
    case 119:
      return jjMoveStringLiteralDfa5_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(3, active0);
  }

  private int jjMoveStringLiteralDfa5_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(3, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(4, active0);
      return 5;
    }
    switch (curChar) {
    case 105:
      return jjMoveStringLiteralDfa6_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(4, active0);
  }

  private int jjMoveStringLiteralDfa6_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(4, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(5, active0);
      return 6;
    }
    switch (curChar) {
    case 107:
      return jjMoveStringLiteralDfa7_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(5, active0);
  }

  private int jjMoveStringLiteralDfa7_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(5, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(6, active0);
      return 7;
    }
    switch (curChar) {
    case 105:
      return jjMoveStringLiteralDfa8_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(6, active0);
  }

  private int jjMoveStringLiteralDfa8_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(6, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(7, active0);
      return 8;
    }
    switch (curChar) {
    case 62:
      return jjMoveStringLiteralDfa9_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(7, active0);
  }

  private int jjMoveStringLiteralDfa9_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(7, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(8, active0);
      return 9;
    }
    switch (curChar) {
    case 60:
      return jjMoveStringLiteralDfa10_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(8, active0);
  }

  private int jjMoveStringLiteralDfa10_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(8, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(9, active0);
      return 10;
    }
    switch (curChar) {
    case 47:
      return jjMoveStringLiteralDfa11_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(9, active0);
  }

  private int jjMoveStringLiteralDfa11_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(9, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(10, active0);
      return 11;
    }
    switch (curChar) {
    case 112:
      return jjMoveStringLiteralDfa12_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(10, active0);
  }

  private int jjMoveStringLiteralDfa12_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(10, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(11, active0);
      return 12;
    }
    switch (curChar) {
    case 114:
      return jjMoveStringLiteralDfa13_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(11, active0);
  }

  private int jjMoveStringLiteralDfa13_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(11, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(12, active0);
      return 13;
    }
    switch (curChar) {
    case 101:
      return jjMoveStringLiteralDfa14_2(active0, 0x2000000000000L);
    default:
      break;
    }
    return jjStartNfa_2(12, active0);
  }

  private int jjMoveStringLiteralDfa14_2(long old0, long active0) {
    if (((active0 &= old0)) == 0L)
      return jjStartNfa_2(12, old0);
    try {
      curChar = input_stream.readChar();
    } catch (java.io.IOException e) {
      jjStopStringLiteralDfa_2(13, active0);
      return 14;
    }
    switch (curChar) {
    case 62:
      if ((active0 & 0x2000000000000L) != 0L)
        return jjStopAtPos(14, 49);
      break;
    default:
      break;
    }
    return jjStartNfa_2(13, active0);
  }

  private int jjMoveNfa_2(int startState, int curPos) {
    int startsAt = 0;
    jjnewStateCnt = 1;
    int i = 1;
    jjstateSet[0] = startState;
    int kind = 0x7fffffff;
    for (;;) {
      if (++jjround == 0x7fffffff)
        ReInitRounds();
      if (curChar < 64) {
        long l = 1L << curChar;
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if ((0xffffffff00000600L & l) != 0L)
              kind = 48;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else if (curChar < 128) {
        long l = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if ((0x7fffffffbffffffeL & l) != 0L)
              kind = 48;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      } else {
        int hiByte = (int) (curChar >> 8);
        int i1 = hiByte >> 6;
        long l1 = 1L << (hiByte & 077);
        int i2 = (curChar & 0xff) >> 6;
        long l2 = 1L << (curChar & 077);
        do {
          switch (jjstateSet[--i]) {
          case 0:
            if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 48)
              kind = 48;
            break;
          default:
            break;
          }
        } while (i != startsAt);
      }
      if (kind != 0x7fffffff) {
        jjmatchedKind = kind;
        jjmatchedPos = curPos;
        kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
        return curPos;
      try {
        curChar = input_stream.readChar();
      } catch (java.io.IOException e) {
        return curPos;
      }
    }
  }

  static final int[] jjnextStates = {};

  private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2) {
    switch (hiByte) {
    case 0:
      return ((jjbitVec2[i2] & l2) != 0L);
    default:
      if ((jjbitVec0[i1] & l1) != 0L)
        return true;
      return false;
    }
  }

  private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2) {
    switch (hiByte) {
    case 0:
      return ((jjbitVec3[i2] & l2) != 0L);
    default:
      if ((jjbitVec0[i1] & l1) != 0L)
        return true;
      return false;
    }
  }

  /** Token literal values. */
  public static final String[] jjstrLiteralImages = { "", "\40", "\11", "\12\174\53", "\174", "\12", "\12\174\55",
      "\55", "\41", "\41\41", "\174\174", "\173", "\175", "\75", "\47", "\72", "\45", "\43", "\73", "\42",
      "\74\142\162\76\12", "\54", "\133", "\135", "\50", "\51", "\56", "\77", "\57", "\134", "\53", "\74", "\76",
      "\52", "\44", "\137", "\46", "\140", "\176", "\173\174", "\174\175",
      "\74\160\162\145\76\74\156\157\167\151\153\151\76", null, null, null, null, null, null, null,
      "\74\57\156\157\167\151\153\151\76\74\57\160\162\145\76", null, null, null, };

  /** Lexer state names. */
  public static final String[] lexStateNames = { "DEFAULT", "COMMENT", "NOWIKI", "MULTI_LINE", };

  /** Lex State array. */
  public static final int[] jjnewLexState = { -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
      -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, 1, 3, -1, -1, 0,
      -1, -1, 0, -1, 0, -1, };
  static final long[] jjtoToken = { 0x1703ffffffffffL, };
  static final long[] jjtoSkip = { 0x8fc0000000000L, };
  static final long[] jjtoSpecial = { 0x80c0000000000L, };
  protected SimpleCharStream input_stream;
  private final int[] jjrounds = new int[3];
  private final int[] jjstateSet = new int[6];
  private final StringBuffer jjimage = new StringBuffer();
  private StringBuffer image = jjimage;
  private int jjimageLen;
  private int lengthOfMatch;
  protected char curChar;

  /** Constructor. */
  public JavaCCTableParserTokenManager(SimpleCharStream stream) {
    if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
    input_stream = stream;
  }

  /** Constructor. */
  public JavaCCTableParserTokenManager(SimpleCharStream stream, int lexState) {
    this(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream) {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds() {
    int i;
    jjround = 0x80000001;
    for (i = 3; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState) {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState) {
    if (lexState >= 4 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
          TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

  protected Token jjFillToken() {
    final Token t;
    final String curTokenImage;
    final int beginLine;
    final int endLine;
    final int beginColumn;
    final int endColumn;
    String im = jjstrLiteralImages[jjmatchedKind];
    curTokenImage = (im == null) ? input_stream.GetImage() : im;
    beginLine = input_stream.getBeginLine();
    beginColumn = input_stream.getBeginColumn();
    endLine = input_stream.getEndLine();
    endColumn = input_stream.getEndColumn();
    t = Token.newToken(jjmatchedKind, curTokenImage);

    t.beginLine = beginLine;
    t.endLine = endLine;
    t.beginColumn = beginColumn;
    t.endColumn = endColumn;

    return t;
  }

  int curLexState = 0;
  int defaultLexState = 0;
  int jjnewStateCnt;
  int jjround;
  int jjmatchedPos;
  int jjmatchedKind;

  /** Get the next Token. */
  public Token getNextToken() {
    Token specialToken = null;
    Token matchedToken;
    int curPos = 0;

    EOFLoop: for (;;) {
      try {
        curChar = input_stream.BeginToken();
      } catch (java.io.IOException e) {
        jjmatchedKind = 0;
        matchedToken = jjFillToken();
        matchedToken.specialToken = specialToken;
        return matchedToken;
      }
      image = jjimage;
      image.setLength(0);
      jjimageLen = 0;

      switch (curLexState) {
      case 0:
        jjmatchedKind = 0x7fffffff;
        jjmatchedPos = 0;
        curPos = jjMoveStringLiteralDfa0_0();
        break;
      case 1:
        jjmatchedKind = 0x7fffffff;
        jjmatchedPos = 0;
        curPos = jjMoveStringLiteralDfa0_1();
        break;
      case 2:
        jjmatchedKind = 0x7fffffff;
        jjmatchedPos = 0;
        curPos = jjMoveStringLiteralDfa0_2();
        break;
      case 3:
        jjmatchedKind = 0x7fffffff;
        jjmatchedPos = 0;
        curPos = jjMoveStringLiteralDfa0_3();
        break;
      }
      if (jjmatchedKind != 0x7fffffff) {
        if (jjmatchedPos + 1 < curPos)
          input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
          matchedToken = jjFillToken();
          matchedToken.specialToken = specialToken;
          if (jjnewLexState[jjmatchedKind] != -1)
            curLexState = jjnewLexState[jjmatchedKind];
          return matchedToken;
        } else {
          if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
            matchedToken = jjFillToken();
            if (specialToken == null)
              specialToken = matchedToken;
            else {
              matchedToken.specialToken = specialToken;
              specialToken = (specialToken.next = matchedToken);
            }
            SkipLexicalActions(matchedToken);
          } else
            SkipLexicalActions(null);
          if (jjnewLexState[jjmatchedKind] != -1)
            curLexState = jjnewLexState[jjmatchedKind];
          continue EOFLoop;
        }
      }
      int error_line = input_stream.getEndLine();
      int error_column = input_stream.getEndColumn();
      String error_after = null;
      boolean EOFSeen = false;
      try {
        input_stream.readChar();
        input_stream.backup(1);
      } catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
          error_line++;
          error_column = 0;
        } else
          error_column++;
      }
      if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
      }
      throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar,
          TokenMgrError.LEXICAL_ERROR);
    }
  }

  void SkipLexicalActions(Token matchedToken) {
    switch (jjmatchedKind) {
    default:
      break;
    }
  }

  private void jjCheckNAdd(int state) {
    if (jjrounds[state] != jjround) {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
    }
  }

  private void jjAddStates(int start, int end) {
    do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
    } while (start++ != end);
  }

  private void jjCheckNAddTwoStates(int state1, int state2) {
    jjCheckNAdd(state1);
    jjCheckNAdd(state2);
  }

}
