/* Generated By:JavaCC: Do not edit this line. JavaCCParser.java */
package be.devijver.wikipedia.parser.javacc.markup;

import java.util.*;
import be.devijver.wikipedia.parser.ast.*;

public class JavaCCParser implements JavaCCParserConstants {

  final public Document document() throws ParseException {
    Content content;
    Document document = new Document();
    label_1: while (true) {
      switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
      case BOLD_AND_ITALICS_DEMARCATION:
      case BOLD_DEMARCATION:
      case ITALICS_DEMARCATION:
      case CHARACTER:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      content = paragraph();
      document.addContent(content);
    }
    {
      if (true)
        return document;
    }
    throw new Error("Missing return statement in function");
  }

  final private Paragraph paragraph() throws ParseException {
    List contentList = new ArrayList();
    Content content;
    label_2: while (true) {
      content = content();
      contentList.add(content);
      switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
      case BOLD_AND_ITALICS_DEMARCATION:
      case BOLD_DEMARCATION:
      case ITALICS_DEMARCATION:
      case CHARACTER:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
    }
    switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
    case 1:
      jj_consume_token(1);
      break;
    case 0:
      jj_consume_token(0);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    Content[] contents = (Content[]) contentList.toArray(new Content[contentList.size()]);
    {
      if (true)
        return new Paragraph(contents);
    }
    throw new Error("Missing return statement in function");
  }

  final private Content content() throws ParseException {
    Content content;
    if (jj_2_1(3)) {
      content = boldAndItalics();
      {
        if (true)
          return content;
      }
    } else {
      switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
      case BOLD_DEMARCATION:
        content = bold();
        {
          if (true)
            return content;
        }
        break;
      case ITALICS_DEMARCATION:
        content = italics();
        {
          if (true)
            return content;
        }
        break;
      case CHARACTER:
        content = text();
        {
          if (true)
            return content;
        }
        break;
      default:
        jj_la1[3] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
  }

  final private Content contentWithoutItalics() throws ParseException {
    Content content;
    switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
    case BOLD_DEMARCATION:
      content = bold();
      {
        if (true)
          return content;
      }
      break;
    case CHARACTER:
      content = text();
      {
        if (true)
          return content;
      }
      break;
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Content contentWithoutBold() throws ParseException {
    Content content;
    switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
    case ITALICS_DEMARCATION:
      content = italics();
      {
        if (true)
          return content;
      }
      break;
    case CHARACTER:
      content = text();
      {
        if (true)
          return content;
      }
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final private Content contentWithoutBoldAndItalics() throws ParseException {
    Content content;
    content = text();
    {
      if (true)
        return content;
    }
    throw new Error("Missing return statement in function");
  }

  final private Italics italics() throws ParseException {
    Content content;
    jj_consume_token(ITALICS_DEMARCATION);
    content = contentWithoutItalics();
    jj_consume_token(ITALICS_DEMARCATION);
    {
      if (true)
        return new Italics(new Content[] { content });
    }
    throw new Error("Missing return statement in function");
  }

  final private Bold bold() throws ParseException {
    Content content;
    jj_consume_token(BOLD_DEMARCATION);
    content = contentWithoutBold();
    jj_consume_token(BOLD_DEMARCATION);
    {
      if (true)
        return new Bold(new Content[] { content });
    }
    throw new Error("Missing return statement in function");
  }

  final private Content boldAndItalics() throws ParseException {
    Content content1;
    Content content2;
    Content result;
    String type;
    switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
    case BOLD_AND_ITALICS_DEMARCATION:
      jj_consume_token(BOLD_AND_ITALICS_DEMARCATION);
      content1 = contentWithoutBoldAndItalics();
      switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
      case BOLD_AND_ITALICS_DEMARCATION:
        jj_consume_token(BOLD_AND_ITALICS_DEMARCATION);
        result = new Bold(new Content[] { new Italics(new Content[] { content1 }) });
        break;
      case BOLD_DEMARCATION:
        jj_consume_token(BOLD_DEMARCATION);
        content2 = contentWithoutBoldAndItalics();
        jj_consume_token(ITALICS_DEMARCATION);
        result = new Italics(new Content[] { new Bold(new Content[] { content1 }), content2 });
        break;
      case ITALICS_DEMARCATION:
        jj_consume_token(ITALICS_DEMARCATION);
        content2 = contentWithoutBoldAndItalics();
        jj_consume_token(BOLD_DEMARCATION);
        result = new Bold(new Content[] { new Italics(new Content[] { content1 }), content2 });
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case BOLD_DEMARCATION:
    case ITALICS_DEMARCATION:
      switch ((jj_ntk == -1) ? jj_ntk() : jj_ntk) {
      case ITALICS_DEMARCATION:
        jj_consume_token(ITALICS_DEMARCATION);
        content1 = contentWithoutBoldAndItalics();
        jj_consume_token(BOLD_DEMARCATION);
        type = "italics";
        break;
      case BOLD_DEMARCATION:
        jj_consume_token(BOLD_DEMARCATION);
        content1 = contentWithoutBoldAndItalics();
        jj_consume_token(ITALICS_DEMARCATION);
        type = "bold";
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      content2 = contentWithoutBoldAndItalics();
      jj_consume_token(BOLD_AND_ITALICS_DEMARCATION);
      if (type.equals("italics")) {
        result = new Italics(new Content[] { content1, new Bold(new Content[] { content2 }) });
      } else if (type.equals("bold")) {
        result = new Bold(new Content[] { content1, new Italics(new Content[] { content2 }) });

      } else {
        {
          if (true)
            throw new RuntimeException("Parser bug!!");
        }
      }
      break;
    default:
      jj_la1[8] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    {
      if (true)
        return result;
    }
    throw new Error("Missing return statement in function");
  }

  final private Characters text() throws ParseException {
    Token t;
    StringBuffer sb = new StringBuffer();
    label_3: while (true) {
      t = jj_consume_token(CHARACTER);
      sb.append(t.image);
      if (jj_2_2(2)) {
        ;
      } else {
        break label_3;
      }
    }
    {
      if (true)
        return new Characters(sb.toString());
    }
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return !jj_3_1();
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(0, xla);
    }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla;
    jj_lastpos = jj_scanpos = token;
    try {
      return !jj_3_2();
    } catch (LookaheadSuccess ls) {
      return true;
    } finally {
      jj_save(1, xla);
    }
  }

  private boolean jj_3R_13() {
    Token xsp;
    if (jj_3_2())
      return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_2()) {
        jj_scanpos = xsp;
        break;
      }
    }
    return false;
  }

  private boolean jj_3R_5() {
    if (jj_scan_token(BOLD_AND_ITALICS_DEMARCATION))
      return true;
    if (jj_3R_7())
      return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_8()) {
      jj_scanpos = xsp;
      if (jj_3R_9()) {
        jj_scanpos = xsp;
        if (jj_3R_10())
          return true;
      }
    }
    return false;
  }

  private boolean jj_3R_9() {
    if (jj_scan_token(BOLD_DEMARCATION))
      return true;
    return false;
  }

  private boolean jj_3R_6() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_11()) {
      jj_scanpos = xsp;
      if (jj_3R_12())
        return true;
    }
    return false;
  }

  private boolean jj_3R_7() {
    if (jj_3R_13())
      return true;
    return false;
  }

  private boolean jj_3R_12() {
    if (jj_scan_token(BOLD_DEMARCATION))
      return true;
    if (jj_3R_7())
      return true;
    if (jj_scan_token(ITALICS_DEMARCATION))
      return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(ITALICS_DEMARCATION))
      return true;
    return false;
  }

  private boolean jj_3R_4() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_5()) {
      jj_scanpos = xsp;
      if (jj_3R_6())
        return true;
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_4())
      return true;
    return false;
  }

  private boolean jj_3R_8() {
    if (jj_scan_token(BOLD_AND_ITALICS_DEMARCATION))
      return true;
    return false;
  }

  private boolean jj_3R_11() {
    if (jj_scan_token(ITALICS_DEMARCATION))
      return true;
    if (jj_3R_7())
      return true;
    if (jj_scan_token(BOLD_DEMARCATION))
      return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_scan_token(CHARACTER))
      return true;
    return false;
  }

  /** Generated Token Manager. */
  public JavaCCParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static {
    jj_la1_init_0();
  }

  private static void jj_la1_init_0() {
    jj_la1_0 = new int[] { 0x3c, 0x3c, 0x3, 0x38, 0x28, 0x30, 0x1c, 0x18, 0x1c, };
  }

  final private JJCalls[] jj_2_rtns = new JJCalls[2];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public JavaCCParser(java.io.InputStream stream) {
    this(stream, null);
  }

  /** Constructor with InputStream and supplied encoding */
  public JavaCCParser(java.io.InputStream stream, String encoding) {
    try {
      jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1);
    } catch (java.io.UnsupportedEncodingException e) {
      throw new RuntimeException(e);
    }
    token_source = new JavaCCParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
    ReInit(stream, null);
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try {
      jj_input_stream.ReInit(stream, encoding, 1, 1);
    } catch (java.io.UnsupportedEncodingException e) {
      throw new RuntimeException(e);
    }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public JavaCCParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new JavaCCParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public JavaCCParser(JavaCCParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JavaCCParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++)
      jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++)
      jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen)
              c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error {
  }

  final private LookaheadSuccess jj_ls = new LookaheadSuccess();

  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0;
      Token tok = token;
      while (tok != null && tok != jj_scanpos) {
        i++;
        tok = tok.next;
      }
      if (tok != null)
        jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind)
      return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos)
      throw jj_ls;
    return false;
  }

  /** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null)
      token = token.next;
    else
      token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  /** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null)
        t = t.next;
      else
        t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt = token.next) == null)
      return (jj_ntk = (token.next = token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100)
      return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[]) (it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0)
        jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[6];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 9; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1 << j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 6; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[]) jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 2; i++) {
      try {
        JJCalls p = jj_2_rtns[i];
        do {
          if (p.gen > jj_gen) {
            jj_la = p.arg;
            jj_lastpos = jj_scanpos = p.first;
            switch (i) {
            case 0:
              jj_3_1();
              break;
            case 1:
              jj_3_2();
              break;
            }
          }
          p = p.next;
        } while (p != null);
      } catch (LookaheadSuccess ls) {
      }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) {
        p = p.next = new JJCalls();
        break;
      }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la;
    p.first = token;
    p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
