/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package be.devijver.wikipedia.parser.javacc.markup;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BOLD_AND_ITALICS_DEMARCATION = 2;
  /** RegularExpression Id. */
  int BOLD_DEMARCATION = 3;
  /** RegularExpression Id. */
  int ITALICS_DEMARCATION = 4;
  /** RegularExpression Id. */
  int CHARACTER = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = { "<EOF>", "\"\\n\"", "\"\\\'\\\'\\\'\\\'\\\'\"", "\"\\\'\\\'\\\'\"", "\"\\\'\\\'\"",
      "<CHARACTER>", };

}
